changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Bug Fix 💊
      labels:
        - bug
    - title: Refactoring :hammer:
      labels:
        - refactoring
    - title: Other Changes
      labels:
        - "*"
